### ISSUE TITLE
API for tab

### ISSUE THREAD

**Issue by randomwangran** [protesilaos/beframe#2]
Hi Prot,

Could you open an option for users to apply similar constrain when using a tab in a frame?

Thanks

**Comment by protesilaos** [comment]
Hello @randomwangran!

Beframe only works with frames.  For tabs there is this package by Colin McLear: https://github.com/mclear-tools/tabspaces

Providing such an option is not trivial work because we need to add all the checks for tab-bar-mode.  That will broaden the scope of the package and make it harder to maintain.

**Comment by randomwangran** [comment]
Thanks for sharing about knowledge about tabspaces. That is more suitable for the task.
